[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules .pnpm-store && pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
